spring:
  #application:
    #name: shiro
  datasource:
    master:
        name: ztm
        url: jdbc:mysql://127.0.0.1:3306/zkmkt?useUnicode=true&characterEncoding=gbk&autoReconnect=true&allowMultiQueries=true
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 50
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
    slave:
        name: ztm
        url: jdbc:mysql://127.0.0.1:3306/dev?useUnicode=true&characterEncoding=gbk&autoReconnect=true&allowMultiQueries=true
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 50
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        
mybatis:
        mapperLocations: classpath*:com/gwg/shiro/web/mapper/*.xml
        typeAliasesPackage: com.gwg.shiro.web.model

server:
  port: 8080
